__title__ = 'harold'
__description__ = 'An open-source systems and controls toolbox for Python3.'
__version__ = '1.0.2'
__author__ = 'Ilhan Polat'
__author_email__ = 'harold.of.python@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022 Ilhan Polat'
