# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Harold Tests

on:
  push:
    branches:
      - main
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Python
    if: "github.repository == 'ilayn/harold' || github.repository == ''"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: show-python-version
      run: |
        python --version
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install library
      run: poetry install
    - name: Run tests
      run: |
        poetry run python -m pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: show-python-version
        run: |
          python -m pip install pip --upgrade
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          flake8
